# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e0b48cd23c5e1fd8de9f11f6a193ca5bd9f3ea2c885ad2da1585a13e9f092ddd16994b9ad546496a67cfafaaeca4aa1e5b2922eb43b3b988e5f00a4808a1627

test:
  secret_key_base: 428d879fd1fba64a9ab4f561b0b775ae81f31b4105c4b6ce109c160e1ee315a273d46595ab61f02c2636fa7289d82bcc96343228e7d6347296ddcbaf525c4c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ba4d5e96471c11b08863cf73ee85dfb878257db414e010f79c7d53bb64fb87f2f040405ace9271e598dbed6a035b389b6dd46bacee5e84a74ff52f3638459413
